- name: install i3
  package:
    name: i3
    state: present

- name: copy i3 configuration
  template:
    src: files/i3.conf.j2
    dest: ~/.config/i3/config

- name: copy xinitrc
  copy:
    src: xinitrc
    dest: ~/.xinitrc
